{"name": "Arbutus West Animal Clinic", "total_annual_cases": "1500", "avg_daily_cases": "8-12", "avg_daily_outpatient_cases": "10-12", "avg_daily_inpatient_cases": "1", "avg_daily_surgeries": "1", "avg_daily_ER_cases": "0.1"}
{"name": "Animal Medical Hospital", "total_annual_cases": "36,500", "avg_daily_cases": "100", "avg_daily_outpatient_cases": "80", "avg_daily_inpatient_cases": "8", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "24"}
{"name": "The Animal Medical Center", "total_annual_cases": "51000", "avg_daily_cases": "145", "avg_daily_outpatient_cases": "125", "avg_daily_inpatient_cases": "50", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "45"}
{"name": "Animal Emergency and Referral Center of Minnesota", "total_annual_cases": "16,104", "avg_daily_cases": "43", "avg_daily_outpatient_cases": "28", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "4", "avg_daily_ER_cases": "25"}
{"name": "Angell Animal Medical Center", "total_annual_cases": "77,629", "avg_daily_cases": "212", "avg_daily_outpatient_cases": "153", "avg_daily_inpatient_cases": "59", "avg_daily_surgeries": "20", "avg_daily_ER_cases": "62"}
{"name": "Angell Animal Medical Center", "total_annual_cases": "2400", "avg_daily_cases": "10", "avg_daily_outpatient_cases": "10", "avg_daily_inpatient_cases": "0", "avg_daily_surgeries": "2", "avg_daily_ER_cases": "1"}
{"name": "Alvarado Veterinary Clinic", "total_annual_cases": "60,000", "avg_daily_cases": "160", "avg_daily_outpatient_cases": "115", "avg_daily_inpatient_cases": "45", "avg_daily_surgeries": "22", "avg_daily_ER_cases": "5"}
{"name": "Affiliated Veterinary Specialists", "total_annual_cases": "12000", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "35", "avg_daily_inpatient_cases": "25", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "5"}
{"name": "Advanced Veterinary Specialists", "total_annual_cases": "12,045", "avg_daily_cases": "33", "avg_daily_outpatient_cases": "20", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "10"}
{"name": "1st Pet Veterinary Centers", "total_annual_cases": "37000", "avg_daily_cases": "100", "avg_daily_outpatient_cases": "60", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "50"}
{"name": "BluePearl Veterinary Partners DC Metro", "total_annual_cases": "17,000", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "32", "avg_daily_inpatient_cases": "8", "avg_daily_surgeries": "3", "avg_daily_ER_cases": "14"}
{"name": "Bluegrass Veterinary Specialists + Animal Emergency", "total_annual_cases": "15,000", "avg_daily_cases": "30-40", "avg_daily_outpatient_cases": "20", "avg_daily_inpatient_cases": "10-12", "avg_daily_surgeries": "3", "avg_daily_ER_cases": "15-20"}
{"name": "Avets", "total_annual_cases": "15354", "avg_daily_cases": "42", "avg_daily_outpatient_cases": "35", "avg_daily_inpatient_cases": "7", "avg_daily_surgeries": "2", "avg_daily_ER_cases": "32"}
{"name": "Auburn University", "total_annual_cases": "16000", "avg_daily_cases": "60", "avg_daily_outpatient_cases": "25-35", "avg_daily_inpatient_cases": "100", "avg_daily_surgeries": "6-10", "avg_daily_ER_cases": "5-15"}
{"name": "Atlantic Veterinary College, University of Prince Edward Island", "total_annual_cases": "4752", "avg_daily_cases": "20", "avg_daily_outpatient_cases": "15", "avg_daily_inpatient_cases": "9", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "5"}
{"name": "Atlantic Coast Veterinary Specialists", "total_annual_cases": "20,000", "avg_daily_cases": "35", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "7", "avg_daily_surgeries": "4", "avg_daily_ER_cases": "15"}
{"name": "Aspen Meadow Veterinary Specialists", "total_annual_cases": "9600", "avg_daily_cases": "24", "avg_daily_outpatient_cases": "12", "avg_daily_inpatient_cases": "8", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "8"}
{"name": "ASPCA Animal Hospital", "total_annual_cases": "20,191", "avg_daily_cases": "51", "avg_daily_outpatient_cases": "20", "avg_daily_inpatient_cases": "22", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "30"}
{"name": "Artemis Veterinary Emergency and Specialty Services", "total_annual_cases": "3400", "avg_daily_cases": "10", "avg_daily_outpatient_cases": "6", "avg_daily_inpatient_cases": "5", "avg_daily_surgeries": "2", "avg_daily_ER_cases": "10"}
{"name": "Arizona Veterinary Emergency & Critical Care Center / BluePearl Veterinary Partners Arizona", "total_annual_cases": "44,022", "avg_daily_cases": "120", "avg_daily_outpatient_cases": "95", "avg_daily_inpatient_cases": "26", "avg_daily_surgeries": "7", "avg_daily_ER_cases": "120"}
{"name": "BluePearl Veterinary Partners New York", "total_annual_cases": "57000", "avg_daily_cases": "156", "avg_daily_outpatient_cases": "101", "avg_daily_inpatient_cases": "48", "avg_daily_surgeries": "22", "avg_daily_ER_cases": "60"}
{"name": "BluePearl Veterinary Partners Nashville", "total_annual_cases": "17,000", "avg_daily_cases": "60", "avg_daily_outpatient_cases": "50", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "20"}
{"name": "BluePearl Veterinary Partners Minnesota", "total_annual_cases": "12,000", "avg_daily_cases": "30-50", "avg_daily_outpatient_cases": "20-40", "avg_daily_inpatient_cases": "15-30", "avg_daily_surgeries": "4-9", "avg_daily_ER_cases": "0"}
{"name": "BluePearl Veterinary Partners Michigan (SF)", "total_annual_cases": "25000", "avg_daily_cases": "70", "avg_daily_outpatient_cases": "60", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "20"}
{"name": "BluePearl Veterinary Partners Michigan (GR)", "total_annual_cases": "18336", "avg_daily_cases": "51", "avg_daily_outpatient_cases": "42", "avg_daily_inpatient_cases": "9", "avg_daily_surgeries": "3", "avg_daily_ER_cases": "22"}
{"name": "BluePearl Veterinary Partners Michigan (GR)", "total_annual_cases": "18336", "avg_daily_cases": "51", "avg_daily_outpatient_cases": "42", "avg_daily_inpatient_cases": "9", "avg_daily_surgeries": "3", "avg_daily_ER_cases": "22"}
{"name": "BluePearl Veterinary Partners Kirkland", "total_annual_cases": "9000", "avg_daily_cases": "55", "avg_daily_outpatient_cases": "35", "avg_daily_inpatient_cases": "35", "avg_daily_surgeries": "7-9", "avg_daily_ER_cases": "10-15"}
{"name": "BluePearl Veterinary Partners Kentucky", "total_annual_cases": "28,000", "avg_daily_cases": "60-90", "avg_daily_outpatient_cases": "50-70", "avg_daily_inpatient_cases": "15-20", "avg_daily_surgeries": "2-6", "avg_daily_ER_cases": "20-25"}
{"name": "BluePearl Veterinary Partners Georgia", "total_annual_cases": "66000", "avg_daily_cases": "180", "avg_daily_outpatient_cases": "120", "avg_daily_inpatient_cases": "57", "avg_daily_surgeries": "13", "avg_daily_ER_cases": "62"}
{"name": "BluePearl Veterinary Partners Florida", "total_annual_cases": "59000", "avg_daily_cases": "120-160", "avg_daily_outpatient_cases": "85-115", "avg_daily_inpatient_cases": "25-65", "avg_daily_surgeries": "5-12", "avg_daily_ER_cases": "42"}
{"name": "Calusa Veterinary Center", "total_annual_cases": "26000", "avg_daily_cases": "75", "avg_daily_outpatient_cases": "60", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "3", "avg_daily_ER_cases": "15-30"}
{"name": "California Veterinary Specialists, Carlsbad", "total_annual_cases": "10,000", "avg_daily_cases": "15", "avg_daily_outpatient_cases": "10", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "10"}
{"name": "California Veterinary Specialists", "total_annual_cases": "13,500", "avg_daily_cases": "50", "avg_daily_outpatient_cases": "40", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "30"}
{"name": "Burlington Emergency and Veterinary Specialists (BEVS)", "total_annual_cases": "20000", "avg_daily_cases": "50", "avg_daily_outpatient_cases": "40", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "2", "avg_daily_ER_cases": "30"}
{"name": "BluePearl Veterinary Partners-Kansas City", "total_annual_cases": "25,880", "avg_daily_cases": "20-50", "avg_daily_outpatient_cases": "20-30", "avg_daily_inpatient_cases": "7-20", "avg_daily_surgeries": "3-9", "avg_daily_ER_cases": "40"}
{"name": "BluePearl Veterinary Partners Virginia/Greenbrier Veterinary Referral Center", "total_annual_cases": "15,500", "avg_daily_cases": "40 - 42", "avg_daily_outpatient_cases": "39", "avg_daily_inpatient_cases": "26", "avg_daily_surgeries": "10 - 15", "avg_daily_ER_cases": "39"}
{"name": "BluePearl Veterinary Partners Spring", "total_annual_cases": "15,000", "avg_daily_cases": "55", "avg_daily_outpatient_cases": "40", "avg_daily_inpatient_cases": "25", "avg_daily_surgeries": "6-8", "avg_daily_ER_cases": "15"}
{"name": "BluePearl Veterinary Partners San Antonio", "total_annual_cases": "14,250", "avg_daily_cases": "55", "avg_daily_outpatient_cases": "25", "avg_daily_inpatient_cases": "45", "avg_daily_surgeries": "12", "avg_daily_ER_cases": "8"}
{"name": "BluePearl Veterinary Partners Richmond", "total_annual_cases": "10-15000", "avg_daily_cases": "30-45", "avg_daily_outpatient_cases": "20-30", "avg_daily_inpatient_cases": "8-15", "avg_daily_surgeries": "8-15", "avg_daily_ER_cases": "10-25"}
{"name": "BluePearl Veterinary Partners Oklahoma", "total_annual_cases": "19,500", "avg_daily_cases": "40-65", "avg_daily_outpatient_cases": "20-40", "avg_daily_inpatient_cases": "10-30", "avg_daily_surgeries": "4-9", "avg_daily_ER_cases": "25"}
{"name": "Cornell University", "total_annual_cases": "19000", "avg_daily_cases": "52", "avg_daily_outpatient_cases": "26", "avg_daily_inpatient_cases": "23", "avg_daily_surgeries": "9", "avg_daily_ER_cases": "11"}
{"name": "CORAL SPRINGS ANIMAL HOSPITAL", "total_annual_cases": "59,720", "avg_daily_cases": "       163", "avg_daily_outpatient_cases": "       130", "avg_daily_inpatient_cases": "         25", "avg_daily_surgeries": "         12", "avg_daily_ER_cases": "       28"}
{"name": "Conejo Valley Veterinary Hospital", "total_annual_cases": "50,000", "avg_daily_cases": "150", "avg_daily_outpatient_cases": "145", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "15"}
{"name": "Columbia Pike Animal Hospital", "total_annual_cases": "3000", "avg_daily_cases": "12", "avg_daily_outpatient_cases": "10", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "2", "avg_daily_ER_cases": "11"}
{"name": "Colorado State University Veterinary Teaching Hospital", "total_annual_cases": "4,839", "avg_daily_cases": "13", "avg_daily_outpatient_cases": "9", "avg_daily_inpatient_cases": "4", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "14"}
{"name": "Center for Veterinary Specialty + Emergency Care", "total_annual_cases": "10889", "avg_daily_cases": "30", "avg_daily_outpatient_cases": "12", "avg_daily_inpatient_cases": "18", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "10"}
{"name": "Center for Animal Referral and Emergency Services", "total_annual_cases": "25000", "avg_daily_cases": "50", "avg_daily_outpatient_cases": "10", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "1", "avg_daily_ER_cases": "10"}
{"name": "Carolina Veterinary Specialists- Winston Salem ", "total_annual_cases": "45000", "avg_daily_cases": "50", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "40"}
{"name": "Carolina Veterinary Specialists", "total_annual_cases": "60,000", "avg_daily_cases": "80-100", "avg_daily_outpatient_cases": "40-50", "avg_daily_inpatient_cases": "50-60", "avg_daily_surgeries": "15-20", "avg_daily_ER_cases": "30-40"}
{"name": "Capital Veterinary Specialists - Tallahassee", "total_annual_cases": "10,000", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "5"}
{"name": "Greater Staten Island Veterinary Services", "total_annual_cases": "8000", "avg_daily_cases": "20-25", "avg_daily_outpatient_cases": "15", "avg_daily_inpatient_cases": "7", "avg_daily_surgeries": "1-3", "avg_daily_ER_cases": "15"}
{"name": "University of Georgia", "total_annual_cases": "22068", "avg_daily_cases": "82", "avg_daily_outpatient_cases": "46", "avg_daily_inpatient_cases": "67", "avg_daily_surgeries": "24", "avg_daily_ER_cases": "8"}
{"name": "University of Georgia", "total_annual_cases": "22068", "avg_daily_cases": "82", "avg_daily_outpatient_cases": "46", "avg_daily_inpatient_cases": "67", "avg_daily_surgeries": "24", "avg_daily_ER_cases": "8"}
{"name": "Garden State Veterinary Specialists", "total_annual_cases": "60000", "avg_daily_cases": "181", "avg_daily_outpatient_cases": "145", "avg_daily_inpatient_cases": "73", "avg_daily_surgeries": "14", "avg_daily_ER_cases": "30-34"}
{"name": "Friendship Hospital for Animals", "total_annual_cases": "61,011", "avg_daily_cases": "167", "avg_daily_outpatient_cases": "140", "avg_daily_inpatient_cases": "17", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "38"}
{"name": "Florida Veterinary Referral Center & 24-Hour Emergency and Critical Care", "total_annual_cases": "20000", "avg_daily_cases": "30", "avg_daily_outpatient_cases": "20", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "3-5", "avg_daily_ER_cases": "15"}
{"name": "University of Florida Veterinary Hospitals", "total_annual_cases": "28,618", "avg_daily_cases": "106", "avg_daily_outpatient_cases": "68", "avg_daily_inpatient_cases": "35", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "36"}
{"name": "Emergency Pet Clinic", "total_annual_cases": "3000", "avg_daily_cases": "10", "avg_daily_outpatient_cases": "4", "avg_daily_inpatient_cases": "4", "avg_daily_surgeries": "1", "avg_daily_ER_cases": "10"}
{"name": "Dogs and Cats Veterinary Referral", "total_annual_cases": "10000", "avg_daily_cases": "30", "avg_daily_outpatient_cases": "15-20", "avg_daily_inpatient_cases": "10-15", "avg_daily_surgeries": "3-5", "avg_daily_ER_cases": "10-20"}
{"name": "The COVE - Center of Veterinary Expertise", "total_annual_cases": "12000", "avg_daily_cases": "30", "avg_daily_outpatient_cases": "15", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "3-5", "avg_daily_ER_cases": "15"}
{"name": "Lakeshore Veterinary Specialists", "total_annual_cases": "10,747", "avg_daily_cases": "29", "avg_daily_outpatient_cases": "10-30", "avg_daily_inpatient_cases": "5-15", "avg_daily_surgeries": "1", "avg_daily_ER_cases": "15-30"}
{"name": "Kansas State University", "total_annual_cases": "12,000", "avg_daily_cases": "45", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "7", "avg_daily_ER_cases": "4-6"}
{"name": "IronHorse VetCare Emergency & Specialty Care Center", "total_annual_cases": "5500", "avg_daily_cases": "15", "avg_daily_outpatient_cases": "10", "avg_daily_inpatient_cases": "4", "avg_daily_surgeries": "2", "avg_daily_ER_cases": "10"}
{"name": "Iowa State University", "total_annual_cases": "20976", "avg_daily_cases": "18", "avg_daily_outpatient_cases": "12", "avg_daily_inpatient_cases": "6", "avg_daily_surgeries": "4", "avg_daily_ER_cases": "8"}
{"name": "Inland Valley Veterinary Specialists", "total_annual_cases": "15000", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "20", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "3-4", "avg_daily_ER_cases": "15-20"}
{"name": "IndyVet Emergency and Specialty Hospital", "total_annual_cases": "8000", "avg_daily_cases": "15-25", "avg_daily_outpatient_cases": "10-15", "avg_daily_inpatient_cases": "10-15", "avg_daily_surgeries": "3-5", "avg_daily_ER_cases": "15"}
{"name": "University of Illinois", "total_annual_cases": "14000", "avg_daily_cases": "75", "avg_daily_outpatient_cases": "50", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "15"}
{"name": "Hope Advanced Veterinary Center-Vienna", "total_annual_cases": "20000", "avg_daily_cases": "55", "avg_daily_outpatient_cases": "33", "avg_daily_inpatient_cases": "22", "avg_daily_surgeries": "5-8", "avg_daily_ER_cases": "14"}
{"name": "Michigan State University - Small Animal", "total_annual_cases": "26852", "avg_daily_cases": "107", "avg_daily_outpatient_cases": "86", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "38"}
{"name": "Miami Veterinary Specialists", "total_annual_cases": "18,000", "avg_daily_cases": "50", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "4", "avg_daily_ER_cases": "20"}
{"name": "Metropolitan Veterinary Specialists and Emergency Services", "total_annual_cases": "12000", "avg_daily_cases": "31", "avg_daily_outpatient_cases": "22", "avg_daily_inpatient_cases": "25", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "20"}
{"name": "Metropolitan Veterinary Hospital / Metropolitan Veterinary Referral Group", "total_annual_cases": "32043", "avg_daily_cases": "87.79", "avg_daily_outpatient_cases": "44", "avg_daily_inpatient_cases": "37", "avg_daily_surgeries": "15", "avg_daily_ER_cases": "25"}
{"name": "Metropolitan Veterinary Hospital / Metropolitan Veterinary Referral Group", "total_annual_cases": "6000-7000", "avg_daily_cases": "15-20", "avg_daily_outpatient_cases": "25", "avg_daily_inpatient_cases": "12", "avg_daily_surgeries": "3-4", "avg_daily_ER_cases": "3-4"}
{"name": "Medvet Medical and Cancer Center for Pets - Louisiana", "total_annual_cases": "11,000", "avg_daily_cases": "60", "avg_daily_outpatient_cases": "25", "avg_daily_inpatient_cases": "35", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "25"}
{"name": "MedVet Medical & Cancer Centers for Pets", "total_annual_cases": "14,000", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "28", "avg_daily_inpatient_cases": "12", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "18"}
{"name": "MedVet Medical & Cancer Centers for Pets", "total_annual_cases": "35,000", "avg_daily_cases": "75", "avg_daily_outpatient_cases": "40", "avg_daily_inpatient_cases": "30", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "56"}
{"name": "Louisiana State University", "total_annual_cases": "19,748", "avg_daily_cases": "76", "avg_daily_outpatient_cases": "66", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "4", "avg_daily_ER_cases": "10"}
{"name": "Long Island Veterinary Specialists", "total_annual_cases": "22,000", "avg_daily_cases": "70", "avg_daily_outpatient_cases": "50", "avg_daily_inpatient_cases": "45", "avg_daily_surgeries": "14", "avg_daily_ER_cases": "15"}
{"name": "NC State University-College of Veterinary Medicine", "total_annual_cases": "32,000", "avg_daily_cases": "83", "avg_daily_outpatient_cases": "31", "avg_daily_inpatient_cases": "52", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "18"}
{"name": "NC State University-College of Veterinary Medicine", "total_annual_cases": "33,586", "avg_daily_cases": "83", "avg_daily_outpatient_cases": "31", "avg_daily_inpatient_cases": "52", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "18"}
{"name": "Nashville Veterinary Specialists", "total_annual_cases": "23140", "avg_daily_cases": "65", "avg_daily_outpatient_cases": "45", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "15"}
{"name": "MSPCA Angell West", "total_annual_cases": "7,651", "avg_daily_cases": "25", "avg_daily_outpatient_cases": "21", "avg_daily_inpatient_cases": "4", "avg_daily_surgeries": "3", "avg_daily_ER_cases": "11"}
{"name": "University of Missouri College of Veterinary Medicine", "total_annual_cases": "1967", "avg_daily_cases": "8", "avg_daily_outpatient_cases": "6", "avg_daily_inpatient_cases": "9", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "1"}
{"name": "University of Missouri College of Veterinary Medicine", "total_annual_cases": "18401", "avg_daily_cases": "71", "avg_daily_outpatient_cases": "62", "avg_daily_inpatient_cases": "34", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "18"}
{"name": "Mississippi State University", "total_annual_cases": "9385", "avg_daily_cases": "30", "avg_daily_outpatient_cases": "15", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "10"}
{"name": "Mississauga Oakville Veterinary Emergency and Referral Services ", "total_annual_cases": "28000", "avg_daily_cases": "72", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "30", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "25"}
{"name": "University of Minnesota, College of Veterinary Medicine", "total_annual_cases": "38,747", "avg_daily_cases": "86", "avg_daily_outpatient_cases": "67", "avg_daily_inpatient_cases": "19", "avg_daily_surgeries": "37", "avg_daily_ER_cases": "15"}
{"name": "Midwestern University", "total_annual_cases": "13000", "avg_daily_cases": "54", "avg_daily_outpatient_cases": "46", "avg_daily_inpatient_cases": "8", "avg_daily_surgeries": "4", "avg_daily_ER_cases": "11"}
{"name": "Pennsylvania Veterinary Specialty and Emergency Associates", "total_annual_cases": "25000", "avg_daily_cases": "62", "avg_daily_outpatient_cases": "60", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "7", "avg_daily_ER_cases": "15"}
{"name": "University of Pennsylvania School of Veterinary Medicine", "total_annual_cases": "30673", "avg_daily_cases": "84", "avg_daily_outpatient_cases": "68", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "30"}
{"name": "Oregon State University", "total_annual_cases": "10,000", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "4", "avg_daily_ER_cases": "4"}
{"name": "Oradell Animal Hospital, Inc. ", "total_annual_cases": "100,000", "avg_daily_cases": "300", "avg_daily_outpatient_cases": "200", "avg_daily_inpatient_cases": "60", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "40"}
{"name": "Ontario Veterinary College Health Sciences Centre", "total_annual_cases": "14519", "avg_daily_cases": "55", "avg_daily_outpatient_cases": "40", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "10"}
{"name": "Oklahoma State University", "total_annual_cases": "12600", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "40", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "9", "avg_daily_ER_cases": "8"}
{"name": "Ohio State University", "total_annual_cases": "26,000", "avg_daily_cases": "80-100", "avg_daily_outpatient_cases": "60-80", "avg_daily_inpatient_cases": "20-40", "avg_daily_surgeries": "10-20", "avg_daily_ER_cases": "20-30"}
{"name": "Ocean State Veterinary Specialists", "total_annual_cases": ">20,000", "avg_daily_cases": "60", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "40", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "50"}
{"name": "New York Veterinary Specialty & Emergency Center", "total_annual_cases": "4000", "avg_daily_cases": "30", "avg_daily_outpatient_cases": "20", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "12", "avg_daily_ER_cases": "5"}
{"name": "New England Animal Medical Center", "total_annual_cases": "16,257", "avg_daily_cases": "50", "avg_daily_outpatient_cases": "32", "avg_daily_inpatient_cases": "18", "avg_daily_surgeries": "12", "avg_daily_ER_cases": "23"}
{"name": "Royal Vista Veterinary Specialists", "total_annual_cases": "3500", "avg_daily_cases": "35", "avg_daily_outpatient_cases": "10", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "15"}
{"name": "Red Bank Veterinary Hospital", "total_annual_cases": "70000", "avg_daily_cases": "192", "avg_daily_outpatient_cases": "168", "avg_daily_inpatient_cases": "24", "avg_daily_surgeries": "27", "avg_daily_ER_cases": "33"}
{"name": "Red Bank Veterinary Hospital", "total_annual_cases": "70000", "avg_daily_cases": "192", "avg_daily_outpatient_cases": "168", "avg_daily_inpatient_cases": "24", "avg_daily_surgeries": "27", "avg_daily_ER_cases": "33"}
{"name": "Purdue University", "total_annual_cases": "19867", "avg_daily_cases": "76", "avg_daily_outpatient_cases": "65", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "12"}
{"name": "Premier Veterinary Group by Ethos", "total_annual_cases": "10358", "avg_daily_cases": "30-35", "avg_daily_outpatient_cases": "25-30", "avg_daily_inpatient_cases": "5-8", "avg_daily_surgeries": "2-5", "avg_daily_ER_cases": "15-30"}
{"name": "Pittsburgh Veterinary Specialty and Emergency Center", "total_annual_cases": "42000", "avg_daily_cases": "125-150", "avg_daily_outpatient_cases": "85", "avg_daily_inpatient_cases": "55-60", "avg_daily_surgeries": "15-20", "avg_daily_ER_cases": "25-40"}
{"name": "Pieper Memorial Veterinary Hospitals", "total_annual_cases": "83,548", "avg_daily_cases": "257", "avg_daily_outpatient_cases": "92", "avg_daily_inpatient_cases": "69", "avg_daily_surgeries": "11", "avg_daily_ER_cases": "20"}
{"name": "Pet+ER", "total_annual_cases": "15,000", "avg_daily_cases": "10-12", "avg_daily_outpatient_cases": "20", "avg_daily_inpatient_cases": "10-12", "avg_daily_surgeries": "2-3", "avg_daily_ER_cases": "20+"}
{"name": "Pet Specialists of Monterey", "total_annual_cases": "8000", "avg_daily_cases": "20", "avg_daily_outpatient_cases": "13", "avg_daily_inpatient_cases": "8", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "12"}
{"name": "Pet Emergency and Specialty Center", "total_annual_cases": "20,000", "avg_daily_cases": "55", "avg_daily_outpatient_cases": "25", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "6-8", "avg_daily_ER_cases": "30"}
{"name": "VCA Alameda East Veterinary Hospital", "total_annual_cases": "50000", "avg_daily_cases": "150", "avg_daily_outpatient_cases": "125", "avg_daily_inpatient_cases": "25", "avg_daily_surgeries": "4", "avg_daily_ER_cases": "60"}
{"name": "VCA Advanced Veterinary Care Center", "total_annual_cases": "15,800", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "35", "avg_daily_inpatient_cases": "12", "avg_daily_surgeries": "12", "avg_daily_ER_cases": "25"}
{"name": "Valley Cottage Animal Hospital", "total_annual_cases": "21,166", "avg_daily_cases": "81", "avg_daily_outpatient_cases": "61", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "20"}
{"name": "Tuskegee University", "total_annual_cases": "9450", "avg_daily_cases": "45", "avg_daily_outpatient_cases": "35", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "3"}
{"name": "Tufts Veterinary Treatment & Specialties", "total_annual_cases": "18,000", "avg_daily_cases": "50", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "25"}
{"name": "Tufts University, Cummings School of Vet. Medicine", "total_annual_cases": "34,724", "avg_daily_cases": "90-100", "avg_daily_outpatient_cases": "75-80", "avg_daily_inpatient_cases": "50", "avg_daily_surgeries": "10-16", "avg_daily_ER_cases": "30-40"}
{"name": "Texas A&M University", "total_annual_cases": "21,426", "avg_daily_cases": "86", "avg_daily_outpatient_cases": "68", "avg_daily_inpatient_cases": "17", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "20"}
{"name": "University of Tennessee", "total_annual_cases": "16,601", "avg_daily_cases": "45", "avg_daily_outpatient_cases": "37", "avg_daily_inpatient_cases": "26", "avg_daily_surgeries": "3", "avg_daily_ER_cases": "8"}
{"name": "Southern California Veterinary Specialty Hospital", "total_annual_cases": "27,000", "avg_daily_cases": "68", "avg_daily_outpatient_cases": "18", "avg_daily_inpatient_cases": "44", "avg_daily_surgeries": "16", "avg_daily_ER_cases": "14"}
{"name": "Southern Arizona Veterinary Specialty and Emergency Center", "total_annual_cases": "27,000", "avg_daily_cases": "74", "avg_daily_outpatient_cases": "66", "avg_daily_inpatient_cases": "14", "avg_daily_surgeries": "3-5", "avg_daily_ER_cases": "25-35"}
{"name": "VCA Canada Calgary Animal Referral and Emergency (C.A.R.E.) Centre", "total_annual_cases": "15000", "avg_daily_cases": "40-50", "avg_daily_outpatient_cases": "25-30", "avg_daily_inpatient_cases": "10-20", "avg_daily_surgeries": "5-10", "avg_daily_ER_cases": "15-20"}
{"name": "VCA Canada 404 Veterinary Emergency and Referral Hospital", "total_annual_cases": "12000", "avg_daily_cases": "32", "avg_daily_outpatient_cases": "25", "avg_daily_inpatient_cases": "12", "avg_daily_surgeries": "3-4", "avg_daily_ER_cases": "12"}
{"name": "VCA Aurora Animal Hospital", "total_annual_cases": "33,000", "avg_daily_cases": "90", "avg_daily_outpatient_cases": "83", "avg_daily_inpatient_cases": "7", "avg_daily_surgeries": "9", "avg_daily_ER_cases": "25"}
{"name": "VCA Arboretum View Animal Hospital", "total_annual_cases": "30,000", "avg_daily_cases": "80", "avg_daily_outpatient_cases": "65", "avg_daily_inpatient_cases": "8-15", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "20"}
{"name": "VCA Animal Specialty Group, San Diego", "total_annual_cases": "13500", "avg_daily_cases": "45", "avg_daily_outpatient_cases": "25", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "3-4", "avg_daily_ER_cases": "10"}
{"name": "VCA Animal Specialty Group, Los Angeles", "total_annual_cases": "15000", "avg_daily_cases": "55", "avg_daily_outpatient_cases": "20-30", "avg_daily_inpatient_cases": "15-20", "avg_daily_surgeries": "4-8/", "avg_daily_ER_cases": "9-20"}
{"name": "VCA Animal Specialty Group, Los Angeles", "total_annual_cases": "15000", "avg_daily_cases": "50", "avg_daily_outpatient_cases": "20-30", "avg_daily_inpatient_cases": "15-20", "avg_daily_surgeries": "4-8", "avg_daily_ER_cases": "9-20"}
{"name": "VCA Animal Specialty & Emergency Center", "total_annual_cases": "12000", "avg_daily_cases": "45-60", "avg_daily_outpatient_cases": "30-35", "avg_daily_inpatient_cases": "12-15", "avg_daily_surgeries": "4-7", "avg_daily_ER_cases": "15-20"}
{"name": "VCA Animal Referral & Emergency Center of Arizona", "total_annual_cases": "12,000", "avg_daily_cases": "32", "avg_daily_outpatient_cases": "20", "avg_daily_inpatient_cases": "8-12", "avg_daily_surgeries": "8-10", "avg_daily_ER_cases": "20-25"}
{"name": "VCA Alexandria Animal Hospital", "total_annual_cases": "36,000-40,000", "avg_daily_cases": "95-110", "avg_daily_outpatient_cases": "80-90", "avg_daily_inpatient_cases": "10-15", "avg_daily_surgeries": "2-4", "avg_daily_ER_cases": "25-35"}
{"name": "VCA South Shore Animal Hospital", "total_annual_cases": "32,900", "avg_daily_cases": "90", "avg_daily_outpatient_cases": "70", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "12", "avg_daily_ER_cases": "32"}
{"name": "VCA Shoreline & VCA Norwalk Veterinary Referral and Emergency Centers", "total_annual_cases": "25000", "avg_daily_cases": "75", "avg_daily_outpatient_cases": "60", "avg_daily_inpatient_cases": "30", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "30"}
{"name": "VCA San Francisco Veterinary Specialists", "total_annual_cases": "22000", "avg_daily_cases": "60", "avg_daily_outpatient_cases": "50", "avg_daily_inpatient_cases": "12", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "20"}
{"name": "VCA Sacramento Veterinary Referral Center", "total_annual_cases": "18250", "avg_daily_cases": "50", "avg_daily_outpatient_cases": "32", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "20"}
{"name": "VCA PetCare Veterinary Hospital", "total_annual_cases": "24,559", "avg_daily_cases": "69", "avg_daily_outpatient_cases": "45", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "28"}
{"name": "VCA Northwest Veterinary Specialists ", "total_annual_cases": "35,000", "avg_daily_cases": "95", "avg_daily_outpatient_cases": "75", "avg_daily_inpatient_cases": "45", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "44"}
{"name": "VCA Loomis Basin Veterinary Clinic ", "total_annual_cases": "65000", "avg_daily_cases": "180", "avg_daily_outpatient_cases": "125", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "15", "avg_daily_ER_cases": "20"}
{"name": "VCA Hollywood Animal Hospital", "total_annual_cases": "35000", "avg_daily_cases": "110", "avg_daily_outpatient_cases": "70", "avg_daily_inpatient_cases": "40", "avg_daily_surgeries": "15", "avg_daily_ER_cases": "14"}
{"name": "VCA Emergency Animal Hospital & Referral Center", "total_annual_cases": "14285", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "10", "avg_daily_surgeries": "4", "avg_daily_ER_cases": "30"}
{"name": "VCA Canada Western Veterinary Specialist and Emergency Centre", "total_annual_cases": "10,000", "avg_daily_cases": "27", "avg_daily_outpatient_cases": "13", "avg_daily_inpatient_cases": "14", "avg_daily_surgeries": "2", "avg_daily_ER_cases": "14"}
{"name": "Veterinary Emergency Clinic/ Referral Centre", "total_annual_cases": "15000", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "35", "avg_daily_inpatient_cases": "40", "avg_daily_surgeries": "9", "avg_daily_ER_cases": "20"}
{"name": "Veterinary Emergency and Specialty Center of New Mexico", "total_annual_cases": "10,000", "avg_daily_cases": "30", "avg_daily_outpatient_cases": "18", "avg_daily_inpatient_cases": "12", "avg_daily_surgeries": "5-6", "avg_daily_ER_cases": "20"}
{"name": "Veterinary Emergency and Specialty Center", "total_annual_cases": "12180", "avg_daily_cases": "30-35", "avg_daily_outpatient_cases": "20-35", "avg_daily_inpatient_cases": "10-30", "avg_daily_surgeries": "3-4", "avg_daily_ER_cases": "20-25"}
{"name": "Veterinary Emergency and Referral Group", "total_annual_cases": "35000", "avg_daily_cases": "90-110", "avg_daily_outpatient_cases": "40-50", "avg_daily_inpatient_cases": "30-45", "avg_daily_surgeries": "8-12", "avg_daily_ER_cases": "30-40"}
{"name": "VESVSC Wisconsin", "total_annual_cases": "22072", "avg_daily_cases": "60", "avg_daily_outpatient_cases": "45", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "2-5", "avg_daily_ER_cases": "46"}
{"name": "VCA West Los Angeles Animal Hospital", "total_annual_cases": "40,000", "avg_daily_cases": "110", "avg_daily_outpatient_cases": "80", "avg_daily_inpatient_cases": "30", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "20"}
{"name": "VCA Veterinary Referral and Emergency Center of Westbury ", "total_annual_cases": "20000", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "15"}
{"name": "VCA Veterinary Care Animal Hospital and Referral Center", "total_annual_cases": "35,000", "avg_daily_cases": "100", "avg_daily_outpatient_cases": "80", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "40"}
{"name": "VCA Valley Animal Hospital and Emergency Center", "total_annual_cases": "28,000", "avg_daily_cases": "75", "avg_daily_outpatient_cases": "60", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "15", "avg_daily_ER_cases": "20"}
{"name": "VCA Southpaws Veterinary Specialists and Emergency Center", "total_annual_cases": "32,000", "avg_daily_cases": "100", "avg_daily_outpatient_cases": "60", "avg_daily_inpatient_cases": "30", "avg_daily_surgeries": "12", "avg_daily_ER_cases": "30"}
{"name": "Veterinary Specialty Centre of Newfoundland and Labrador", "total_annual_cases": "6000", "avg_daily_cases": "15-30", "avg_daily_outpatient_cases": "10-20", "avg_daily_inpatient_cases": "7-15", "avg_daily_surgeries": "3-6", "avg_daily_ER_cases": "7-20"}
{"name": "Veterinary Specialty Centre of Newfoundland and Labrador", "total_annual_cases": "6000", "avg_daily_cases": "15-30", "avg_daily_outpatient_cases": "10-20", "avg_daily_inpatient_cases": "7-15", "avg_daily_surgeries": "3-6", "avg_daily_ER_cases": "7-20"}
{"name": "Veterinary Specialty Center of Tucson", "total_annual_cases": "17000", "avg_daily_cases": "45", "avg_daily_outpatient_cases": "42", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "7", "avg_daily_ER_cases": "20"}
{"name": "Veterinary Specialty Center of Seattle", "total_annual_cases": "20000", "avg_daily_cases": "56", "avg_daily_outpatient_cases": "31", "avg_daily_inpatient_cases": "25", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "30"}
{"name": "Veterinary Specialty Center of Delaware", "total_annual_cases": "30,000", "avg_daily_cases": "50", "avg_daily_outpatient_cases": "35", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "8", "avg_daily_ER_cases": "25"}
{"name": "Veterinary Specialty Center", "total_annual_cases": "41,600", "avg_daily_cases": "120", "avg_daily_outpatient_cases": "85", "avg_daily_inpatient_cases": "30", "avg_daily_surgeries": "15", "avg_daily_ER_cases": "35"}
{"name": "Veterinary Specialists & Emergency Services", "total_annual_cases": "30000", "avg_daily_cases": "80-120", "avg_daily_outpatient_cases": "40-60", "avg_daily_inpatient_cases": "20-40", "avg_daily_surgeries": "20-30", "avg_daily_ER_cases": "35"}
{"name": "Veterinary Referral Associates", "total_annual_cases": "15000", "avg_daily_cases": "40-50", "avg_daily_outpatient_cases": "25-35", "avg_daily_inpatient_cases": "15-25", "avg_daily_surgeries": "6-10", "avg_daily_ER_cases": "15-25"}
{"name": "Veterinary Medical Center of Long Island", "total_annual_cases": "36000", "avg_daily_cases": "86", "avg_daily_outpatient_cases": "56", "avg_daily_inpatient_cases": "32", "avg_daily_surgeries": "15", "avg_daily_ER_cases": "32"}
{"name": "Veterinary Medical Center of Central New York", "total_annual_cases": "18692", "avg_daily_cases": "51", "avg_daily_outpatient_cases": "35", "avg_daily_inpatient_cases": "16", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "27"}
{"name": "Wisconsin Veterinary Referral Center", "total_annual_cases": "33,400", "avg_daily_cases": "90", "avg_daily_outpatient_cases": "72", "avg_daily_inpatient_cases": "25", "avg_daily_surgeries": "4-5", "avg_daily_ER_cases": "52"}
{"name": "Wilson Veterinary Hospital", "total_annual_cases": "42,000", "avg_daily_cases": "40", "avg_daily_outpatient_cases": "80", "avg_daily_inpatient_cases": "45", "avg_daily_surgeries": "15", "avg_daily_ER_cases": "45"}
{"name": "Wheat Ridge Animal Hospital", "total_annual_cases": "36,000", "avg_daily_cases": "100", "avg_daily_outpatient_cases": "86", "avg_daily_inpatient_cases": "12", "avg_daily_surgeries": "10", "avg_daily_ER_cases": "40"}
{"name": "WestVet Emergency & Specialty Center", "total_annual_cases": "29155", "avg_daily_cases": "80", "avg_daily_outpatient_cases": "44", "avg_daily_inpatient_cases": "30", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "39"}
{"name": "Western College of Veterinary Medicine", "total_annual_cases": "9224", "avg_daily_cases": "37", "avg_daily_outpatient_cases": "25", "avg_daily_inpatient_cases": "12", "avg_daily_surgeries": "2.5", "avg_daily_ER_cases": "17"}
{"name": "West Hills Animal Hospital & Emergency Center", "total_annual_cases": "30000", "avg_daily_cases": "70", "avg_daily_outpatient_cases": "60", "avg_daily_inpatient_cases": "15", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "12"}
{"name": "Virginia-Maryland College of Veterinary Medicine", "total_annual_cases": "13792", "avg_daily_cases": "53", "avg_daily_outpatient_cases": "43", "avg_daily_inpatient_cases": "7", "avg_daily_surgeries": "11", "avg_daily_ER_cases": "3"}
{"name": "Veterinary Specialty Hospital of the Carolinas", "total_annual_cases": "40000", "avg_daily_cases": "60", "avg_daily_outpatient_cases": "50", "avg_daily_inpatient_cases": "20", "avg_daily_surgeries": "6", "avg_daily_ER_cases": "20"}
{"name": "Veterinary Specialty Hospital of San Diego - North County", "total_annual_cases": "11,268", "avg_daily_cases": "31", "avg_daily_outpatient_cases": "28", "avg_daily_inpatient_cases": "6", "avg_daily_surgeries": "2", "avg_daily_ER_cases": "14"}
{"name": "Veterinary Specialty Hospital of San Diego", "total_annual_cases": "22000", "avg_daily_cases": "60", "avg_daily_outpatient_cases": "30", "avg_daily_inpatient_cases": "30", "avg_daily_surgeries": "7", "avg_daily_ER_cases": "20"}
{"name": "University of Wisconsin-Madison School of Veterinary Medicine", "total_annual_cases": "24,937", "avg_daily_cases": "96", "avg_daily_outpatient_cases": "86", "avg_daily_inpatient_cases": "23", "avg_daily_surgeries": "5", "avg_daily_ER_cases": "15"}
